### ISSUE TITLE
No module named 'baselines.common.vec_env.shmem_vec_env'?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [hzaskywalker/PlasticineLab#3]
Tried this out (commit ac1a2f7) on CPython 3.6.9 (Ubuntu 18.04), using sample command:
```
$ python3 -m plb.algorithms.solve --algo action --env_name Move-v1 --path output
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../PlasticineLab/plb/algorithms/solve.py", line 10, in <module>
    from plb.algorithms.ppo.run_ppo import train_ppo
  File ".../PlasticineLab/plb/algorithms/ppo/run_ppo.py", line 15, in <module>
    from plb.algorithms.ppo.ppo import algo, utils
  File ".../PlasticineLab/plb/algorithms/ppo/ppo/algo/__init__.py", line 1, in <module>
    from .a2c_acktr import A2C_ACKTR
  File ".../PlasticineLab/plb/algorithms/ppo/ppo/algo/a2c_acktr.py", line 5, in <module>
    from ..algo.kfac import KFACOptimizer
  File ".../PlasticineLab/plb/algorithms/ppo/ppo/algo/kfac.py", line 8, in <module>
    from ..utils import AddBias
  File ".../PlasticineLab/plb/algorithms/ppo/ppo/utils.py", line 7, in <module>
    from .envs import VecNormalize
  File ".../PlasticineLab/plb/algorithms/ppo/ppo/envs.py", line 12, in <module>
    from baselines.common.vec_env.shmem_vec_env import ShmemVecEnv
ModuleNotFoundError: No module named 'baselines.common.vec_env.shmem_vec_env'
```

Output of `pip freeze`:
https://gist.github.com/EricCousineau-TRI/4994eedbf8c38c657b95cecaa8456d97

**Comment by EricCousineau-TRI** [comment]
Was able to fix by installing `baselines` from git:
```
pip install git+https://github.com/openai/baselines@ea25b9e8
```
